name: Build revised.pdf document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_FFTT }}
        uses: Ilshidur/action-discord@0.0.2
        with:
          args: ${{ github.event.pusher.name }} has pushed ${{ github.event.ref }} at ${{ github.event.compare }}
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: revised.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          working_directory: core/
          extra_packages: "mwe"
