name: Build revised.pdf document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: core/revised.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          working_directory: core/
