name: revised.pdf
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Debug Session
        env:
          TMATE_ENCRYPT_PASSWORD: tempotemp
        uses: tete1030/safe-debugger-action@master
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: revised.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          working_directory: core/
#      - name: Post-Complie AV Scan Current Commit
#        uses: djdefi/gitavscan@master

