name: PR_Review
on:
  pull_request:
    types: [review_requested, reopened, opened, synchronize]
jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_FFTT }}
        uses: Ilshidur/action-discord@0.0.2
        with:
          args: PR ${{ github.event.number}} from ${{ github.actor }} is pending at ${{ github.event.pull_request.html }} with status ${{ github.event.pull_request.status }}
